Answers
yam24bot/qna pull request #6
Opened 2021-01-06 13:30 UTC by yam24bot

2021-01-06 13:44 UTC, AZatsepa requested changes

2021-01-06 13:44 UTC, AZatsepa commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@question)
What if an answer was not created?

2021-01-06 13:44 UTC, AZatsepa commented on app/views/questions/_answers.html.slim
> +  p= answer.body
Set your IDE to add new lines

2021-01-06 13:44 UTC, AZatsepa commented on app/views/questions/show.html.slim
> +  = f.submit 'Create'
Set your IDE to add new lines

2021-01-06 13:44 UTC, AZatsepa commented on db/migrate/20210106101435_create_answers.rb
> +      t.index :question_id
Use reference instead

2021-01-06 13:44 UTC, AZatsepa commented on spec/acceptance/create_answers_spec.rb
> +    expect(page).to have_content 'My answer'
What about cases with validation?

2021-01-06 13:44 UTC, AZatsepa commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@question)
Are you sure that you use AJAX?

2021-01-06 13:44 UTC, AZatsepa commented on spec/rails_helper.rb
> +  Capybara::Selenium::Driver.new(app, browser: :chrome)
Is it convenient to always see tests in a browser?

2021-01-20 10:56 UTC, OmegaLord requested changes

2021-01-20 10:56 UTC, OmegaLord commented on app/views/layouts/_navbar.html.erb
> +</nav>
Setup your IDE

2021-01-20 10:56 UTC, OmegaLord commented on app/views/questions/_answer_form.html.erb
> +
Setup your IDE

2021-01-20 10:56 UTC, OmegaLord commented on app/views/questions/index.html.erb
> +<p> <%= link_to 'Ask question', new_question_path %> <p
Setup your IDE

2021-01-20 10:56 UTC, OmegaLord commented on app/views/questions/show.html.erb
> +<%= render "questions/answer_form"%>
Setup your IDE

2021-01-20 10:56 UTC, OmegaLord commented on spec/acceptance/create_answers_spec.rb
> +  scenario 'Non-authenticated User tries to create answer', js: true do
Move `js: true` to `feature` to DRY

2021-01-20 10:56 UTC, OmegaLord commented on spec/controllers/answers_controller_spec.rb
> +        it 'sends empty params' do
`it "has status unauthorized"`

2021-01-20 10:56 UTC, OmegaLord commented on spec/controllers/answers_controller_spec.rb
> +        it 'does not save the question' do
Does not save the question?

2021-01-20 10:56 UTC, OmegaLord commented on spec/controllers/answers_controller_spec.rb
> +        it 'sends empty params' do
`it "has status success"`

2021-01-20 10:56 UTC, OmegaLord commented on spec/acceptance/create_answers_spec.rb
> +    click_on 'Create'
Try `sleep 2`, after `click_on 'Create'` for passing test

2021-01-20 11:08 UTC, AZatsepa commented on spec/acceptance/create_answers_spec.rb
> +    click_on 'Create'
Don't use `sleep` :)
https://thoughtbot.com/blog/write-reliable-asynchronous-integration-tests-with-capybara

2021-01-21 16:03 UTC, OmegaLord commented on app/views/questions/_answer_form.html.erb
> +    <%=	f.text_area :body, :class => "form-control" %>
Indentation in `<%= %>` is 1 space

2021-01-21 16:09 UTC, OmegaLord commented on spec/acceptance/create_answers_spec.rb
> +  # scenario 'Authenticated user create answer' do
Fix this test with 1 or more clicks on random label or h tag

2021-01-22 14:08 UTC, AZatsepa commented on db/schema.rb
> +    t.index ["{:foreign_key=>true}_id"], name: "index_questions_on_{:foreign_key=>true}_id"
???

2021-01-25 10:53 UTC, OmegaLord approved these changes

2021-01-25 12:04 UTC, OmegaLord requested changes

2021-01-25 12:04 UTC, OmegaLord commented on app/views/questions/_question_form.html.erb
> +    <label for="exampleInputPassword1"><%=	f.label :body %></label>
Remove space between `<%=	f.label `

2021-01-25 12:04 UTC, OmegaLord commented on app/views/questions/_question_form.html.erb
> +    <%=	f.text_area :body, :class => "form-control" %>
Remove space between `<%=	f.text_area`

2021-01-25 12:04 UTC, OmegaLord commented on app/views/questions/index.html.erb
> +<p> <%= link_to 'Ask question', new_question_path %> <p
Close `<p>` with `</p>`

2021-01-25 12:04 UTC, OmegaLord commented on app/views/questions/show.html.erb
> +  <%= render "answers"%>
Add space after `"answers"`

2021-01-25 12:04 UTC, OmegaLord commented on app/views/questions/show.html.erb
> +<%= render "questions/answer_form"%>
Add space after `"questions/answer_form"`

2021-01-25 14:56 UTC, OmegaLord approved these changes

2021-01-26 11:50 UTC, OmegaLord approved these changes

2021-01-26 12:00 UTC, merged